### ISSUE TITLE
Error: package or namespace load failed for ‘tabularaster’:  object ‘cividis’ is not exported by 'namespace:viridisLite'

### ISSUE THREAD

**Issue by NateMietk** [r-gris/tabularaster#18]
Hi,

Tried to load the `library(tabular aster)` and keep getting an error on initiation:

`Error: package or namespace load failed for ‘tabularaster’:
 object ‘cividis’ is not exported by 'namespace:viridisLite'`

I have loaded and installed civics, viridisLite, and viridis and still not working. Any suggestions?

Thanks!
Nate

**Comment by mdsumner** [comment]
Thanks, I've actually seen this in another package of mine and I could not fix it. I think it's ultimately a viridis problem: 

https://github.com/sjmgarnier/viridis/issues/56

so, hopefully the issue will go away soon. 

It might be fixed if you re-install viridisLite from CRAN, so that 0.3.0 of that is available?

**Comment by mdsumner** [comment]
Pretty sure this is fixed now
